# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ILem-no8YGBsRQpOfnm0EqvAJ_itke2F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from google.colab import files
import io

data=files.upload()

# Commented out IPython magic to ensure Python compatibility.
df=pd.read_csv(io.StringIO(data['area-ml.csv'].decode('utf-8')))
df
# %matplotlib inline
plt.xlabel("Area")
plt.ylabel("Price in PKR")
plt.scatter(df.Area,df.Price, color='purple',marker='+')
plt.plot(df.Area,reg.predict(df[['Area']]),color='blue')

reg=linear_model.LinearRegression()
reg.fit(df[['Area']],df.Price)

reg.predict([[3300]])

reg.coef_

reg.intercept_

168.54383652*3300+(-124577.45550428459)